site_name: Poradnik Modelarski
repo_url: https://github.com/Laboratorium-Dextera/poradnik-modelarski/
repo_name: Laboratorium-Dextera/poradnik-modelarski/
edit_uri: edit/main/docs/
theme:
  logo: ./assets/logo.png
  language: pl
  name: material
  custom_dir: overrides
  palette:
    primary: grey
  features:
    - header.autohide
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil 
    view: material/eye
extra:
  consent:
    title: Polityka Bezpieczeństwa 
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.    
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:kontakt@papermodels.eu
  disqus: modelarstwookiemdextera
plugins:
  - privacy
  - git-revision-date-localized:
      enable_creation_date: true
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
copyright: >
  Copyright &copy; 2024 - 2024 DexterLab
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
